
insert into CURRENCY_EXCHANE (CONVERSION_MULTIPLE,ID,CURRENCY_FROM ,CURRENCY_TO ,ENVIRONMENT)
values(79.00,10001,'USD','INR',' ');

insert into CURRENCY_EXCHANE (CONVERSION_MULTIPLE,ID,CURRENCY_FROM ,CURRENCY_TO ,ENVIRONMENT)
values(89.00,10002,'EUR','INR',' ');

insert into CURRENCY_EXCHANE (CONVERSION_MULTIPLE,ID,CURRENCY_FROM ,CURRENCY_TO ,ENVIRONMENT) 
values(25.00,1003,'AUD','INR',' ');